//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeatGross.Interaction_Logic_OR_BIZ
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Meat()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public int Id { get; set; }
        public string meatType { get; set; }
        public int stock { get; set; }
        public decimal price { get; set; }
        public System.DateTime priceDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
    }
}
