//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeatGross.Interaction_Logic_OR_BIZ
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MeatGrossEntities : DbContext
    {
        public MeatGrossEntities()
            : base("name=MeatGrossEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<Meat> Meat { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<ZipCity> ZipCity { get; set; }
    }
}
