//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeatGross.Interaction_Logic_OR_BIZ
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int Id { get; set; }
        public int customer { get; set; }
        public int meat { get; set; }
        public int weight { get; set; }
        public System.DateTime orderDate { get; set; }
        public decimal orderPrice { get; set; }
    
        public virtual Customer Customer1 { get; set; }
        public virtual Meat Meat1 { get; set; }
    }
}
