//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database_and_WPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movies
    {
        public int Id { get; set; }
        public string MovieName { get; set; }
        public int ReleaseYear { get; set; }
        public string Genre { get; set; }
        public string Instructor { get; set; }
        public string Actors { get; set; }
    }
}
