//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsportDanmark_PEO.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EsportDanmarkEntities : DbContext
    {
        public EsportDanmarkEntities()
            : base("name=EsportDanmarkEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Players> Players { get; set; }
        public virtual DbSet<Sponsorer> Sponsorer { get; set; }
        public virtual DbSet<Tournament> Tournament { get; set; }
    }
}
