//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsportDanmark_PEO.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sponsorer
    {
        public int Id { get; set; }
        public string CompanyName { get; set; }
        public string CompanySector { get; set; }
        public int PlayerId { get; set; }
        public decimal SponsorAmount { get; set; }
    
        public virtual Players Players { get; set; }
    }
}
