//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Viking_Rejser_Eksamen.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VikingRejserEksamenEntities : DbContext
    {
        public VikingRejserEksamenEntities()
            : base("name=VikingRejserEksamenEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Kunder> Kunder { get; set; }
        public virtual DbSet<Rejsearrangementer> Rejsearrangementer { get; set; }
        public virtual DbSet<RejseTilmeldinger> RejseTilmeldinger { get; set; }
        public virtual DbSet<Transportoer> Transportoer { get; set; }
    }
}
