//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Viking_Rejser_Eksamen.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transportoer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Transportoer()
        {
            this.Rejsearrangementer = new HashSet<Rejsearrangementer>();
        }
    
        public int Id { get; set; }
        public string Navn { get; set; }
        public string Adresse { get; set; }
        public string TelefonNr { get; set; }
        public string Bemaerkninger { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rejsearrangementer> Rejsearrangementer { get; set; }
    }
}
