//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaveService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Istandsættelse
    {
        public int Id { get; set; }
        public string Kundeadresse { get; set; }
        public System.DateTime Start_Dato { get; set; }
        public System.DateTime Slut_Dato { get; set; }
        public int Pris { get; set; }
        public int Areal_Af_Have { get; set; }
        public string Beskrivelse_af_Opgave { get; set; }
    
        public virtual Kunder Kunder { get; set; }
    }
}
